- name: ArcFaceLoss
  weight: 1.0
  kwargs:
    num_classes: ${experience.n_classes}
    embedding_size: ${model.kwargs.embed_dim}
    margin: 28.6
    scale: 64

- name: SupAP
  weight: 1.0
  kwargs:
    tau: 0.01
    rho: 100.0
    offset: 1.44
    delta: 0.05
