experiment_name: ???
log_dir: /share/DEEPLEARNING/datasets/image_retrieval/experiments/
data_dir: ???
seed: ???
resume: null
maybe_resume: False
force_lr: null

warm_up: -1
warm_up_key: fc

max_iter: 50

train_eval_freq: -1
val_eval_freq: -1
test_eval_freq: 5
eval_bs: 96
save_model: 5
eval_split: test
principal_metric: mean_average_precision_at_r_level0
log_grad: False
with_AP: False
landmarks: False

split: null
kfold: null
split_random_state: null
with_super_labels: False

num_workers: 4
pin_memory: True

sub_batch: 128
update_type: base_update

n_classes:
